<?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?>

<!DOCTYPE Doctor [ 
<!ELEMENT Doctor (name, phone, specialization, investigationalProducts)> 
	<!ATTLIST Doctor email CDATA #REQUIRED> 
    	<!ELEMENT name (#PCDATA)> 
    	<!ELEMENT phone (#PCDATA)> 
    	<!ELEMENT specialization (#PCDATA)> 
    	<!ELEMENT investigationalProducts (investigationalProduct*)> 
    	<!ELEMENT investigationalProduct (amount, description, type)> 
        	<!ELEMENT amount (#PCDATA)> 
        	<!ELEMENT description (#PCDATA)> 
        	<!ELEMENT type (#PCDATA)> 
]>

<Doctor email="anafdez@gmail.com"> 
    <name>Ana</name>
    <phone>610000002</phone>
    <specialization>neurosurgeon</specialization>
    <investigationalProducts> 
        <investigationalProduct>
            <amount>1000</amount>
            <description>Advanced surgical machine</description>
            <type>machine</type>
        </investigationalProduct>
        <investigationalProduct>
            <amount>1020</amount>
            <description>New drug for cure alzheimer</description>
            <type>drug</type>
        </investigationalProduct>
    </investigationalProducts>
</Doctor>