<?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?>


<!DOCTYPE Patient [ 

<!ELEMENT Patient (name, phone, bloodType, disease, cured, doctor, dateOfBirth)> 
      <!ATTLIST Patient email CDATA #REQUIRED> 
          <!ELEMENT name (#PCDATA)> 
          <!ELEMENT phone (#PCDATA)> 
          <!ELEMENT bloodType (#PCDATA)> 
          <!ELEMENT disease (#PCDATA)> 
          <!ELEMENT cured (#PCDATA)> 
          <!ELEMENT doctor (name, phone, specialization, patients, investigationalProducts)> 
          <!ELEMENT dateOfBirth (#PCDATA)> 

          <!ELEMENT Doctor (name, phone, specialization, patients,investigationalProducts)> 
          <!ATTLIST Doctor email CDATA #REQUIRED> 
          <!ELEMENT name (#PCDATA)> 
          <!ELEMENT phone (#PCDATA)> 
          <!ELEMENT specialization (#PCDATA)> 
          <!ELEMENT patients (patient+)> 
          <!ELEMENT patient (#PCDATA)> 
          <!ELEMENT investigationalProducts (investigationalProduct+)> 
          <!ELEMENT investigationalProduct (#PCDATA)>
    ]>


<Patient email = "bradpitt@gmail.com"> 
  <name>Brad</name>
  <phone>612345678</phone>
  <bloodType>A+</bloodType>
  <disease>Parkinson</disease>
  <cured>false</cured>
  <dateOfBirth>1963-12-18</dateOfBirth>
  <doctor email = "juangarcia@gmail.com"> 
    <name>Juan</name>
    <phone>612345678</phone>
    <specialization> Surgeon </specialization>
    <patients> 
      <patient>2</patient>
    </patients>
    <investigationalProducts> 
      <investigationalProduct> machine </investigationalProduct>
    </investigationalProducts>
  </doctor>
</Patient>