<?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?> 

<!DOCTYPE Administrator [ 
<!ELEMENT  Administrator (name, phone, trials)> 
	<!ATTLIST Administrator email CDATA #REQUIRED> 
	<!ELEMENT name (#PCDATA)> 
	<!ELEMENT phone (#PCDATA)> 
	<!ELEMENT trials (trial*)> 
	<!ELEMENT trial (requirements, totalAmountInvested)>
		<!ELEMENT requirements (#PCDATA)>
		<!ELEMENT totalAmountInvested (#PCDATA)>

]>


<Administrator email="rodrigofdez@gmail.com">
    <name>Rodrigo</name>
    <phone>690112119</phone>
    <trials>
        <trial>
            <requirements>Neurological disease</requirements>
            <totalAmountInvested>8000</totalAmountInvested>
        </trial>
        <trial>
			<requirements>early stage, female, family history with the disease (alzheimer)</requirements>
			<totalAmountInvested>120000</totalAmountInvested>
		</trial>
    </trials>
</Administrator>
